pipeline:

  code_inspection:
    image: python:3.6
    commands:
      - pip install -q pylama yapf
      - yapf -dr . | (! grep '.')
      - pylama --skip '*/configs/*'
    when:
      event: push

  build_app_image:
    image: plugins/docker
    registry: registry.shafayouxi.org
    secrets: [ docker_username, docker_password ]
    repo: registry.shafayouxi.org/kevinanew/laiwan_io_web
    tags:
      - latest
      - ${DRONE_COMMIT_SHA}
    dockerfile: Dockerfile
    build_args:
      - "--no-cache"
    when:
      event: push

  build_docker_image_with_tag:
    image: plugins/docker
    registry: registry.shafayouxi.org
    secrets: [ docker_username, docker_password ]
    repo: registry.shafayouxi.org/kevinanew/laiwan_io_web
    dockerfile: Dockerfile
    tags: ${DRONE_TAG##v}
    build_args:
      - "--no-cache"
    when:
      event: tag

  test:
    image: registry.shafayouxi.org/kevinanew/laiwan_io_web
    pull: true
    commands:
      - python src/manage.py test
    when:
      event: push

  deploy_staging_by_commit:
    image: plugins/ansible
    secrets: [ ansible_private_key ]
    inventory: deploy/staging.hosts
    playbook: deploy/staging.yml
    flush_cache: true
    extra_vars: docker_tag=${DRONE_COMMIT_SHA}
    when:
      event: push
      branch: master

  deploy_staging_by_tag:
    image: plugins/ansible
    secrets: [ ansible_private_key ]
    inventory: deploy/staging.hosts
    playbook: deploy/staging.yml
    flush_cache: true
    extra_vars: docker_tag=v${DRONE_TAG##v}
    when:
      event: tag

  deploy_production:
    image: plugins/ansible
    secrets: [ ansible_private_key ]
    inventory: deploy/production.hosts
    playbook: deploy/production.yml
    flush_cache: true
    extra_vars: docker_tag=v${DRONE_TAG##v}
    when:
      event: tag
      branch: master

  telegram:
    image: appleboy/drone-telegram
    token: 483423532:AAFwMDyTAJF1Mbzmm7PA-2LSK4w-9bwFh3I
    to: -1001188725759
    when:
      status: [ failure ]
