pipeline:

  build_staging_by_push_master:
    image: node:8
    commands:
      - cd react_laiwan_com
      - yarn install --ignore-engines
      - yarn build
    when:
      event: push
      branch: master

  build_staging_by_tag:
    image: node:8
    commands:
      - cd react_laiwan_com
      - yarn install --ignore-engines
      - yarn build
    when:
      event: tag
      branch:
        exclude:
          - master

  build_staging_docker_image_by_push_master:
    image: plugins/docker
    registry: registry.eu-central-1.aliyuncs.com
    secrets: [ docker_username, docker_password ]
    repo: registry.eu-central-1.aliyuncs.com/laiwanio/laiwan_io_web
    tags:
      - latest
      - ${DRONE_COMMIT_SHA}
    dockerfile: Dockerfile-release
    when:
      event: push
      branch: master

  build_staging_docker_image_by_tag:
    image: plugins/docker
    registry: registry.eu-central-1.aliyuncs.com
    secrets: [ docker_username, docker_password ]
    repo: registry.eu-central-1.aliyuncs.com/laiwanio/laiwan_io_web
    dockerfile: Dockerfile-release
    tags:
      - latest
      - ${DRONE_TAG##v}
    when:
      event: tag
      branch:
        exclude:
          - master

  deploy_staging_by_push_master:
    image: plugins/ansible
    secrets: [ ansible_private_key ]
    inventory: deploy/staging.hosts
    playbook: deploy/staging.yml
    flush_cache: true
    extra_vars: docker_tag=${DRONE_COMMIT_SHA}
    when:
      event: push
      branch: master

  deploy_staging_by_tag:
    image: plugins/ansible
    secrets: [ ansible_private_key ]
    inventory: deploy/staging.hosts
    playbook: deploy/staging.yml
    flush_cache: true
    extra_vars: docker_tag=${DRONE_TAG##v}
    when:
      event: tag
      branch:
        exclude:
          - master

  build_production_by_tag_master:
    image: node:8
    commands:
      - cd react_laiwan_com
      - yarn install --ignore-engines
      - cp src/config_production.json src/config.json
      - yarn build
    when:
      event: tag
      branch: master

  build_production_docker_image_by_tag_master:
    image: plugins/docker
    registry: registry.eu-central-1.aliyuncs.com
    secrets: [ docker_username, docker_password ]
    repo: registry.eu-central-1.aliyuncs.com/laiwanio/laiwan_io_web
    dockerfile: Dockerfile-release
    tags:
      - latest
      - ${DRONE_TAG##v}
    when:
      event: tag
      branch: master

  deploy_production_by_tag_master:
    image: plugins/ansible
    secrets: [ ansible_private_key ]
    inventory: deploy/production.hosts
    playbook: deploy/production.yml
    flush_cache: true
    extra_vars: docker_tag=${DRONE_TAG##v}
    when:
      event: tag
      branch: master
