kind: pipeline
type: docker
name: default


trigger:
  event:
  - push
  - tag


image_pull_secrets:
- aliyun_hongkong_docker_config


steps:
- name: Build docker image
  image: plugins/docker
  pull: if-not-exists
  settings:
    registry: registry.cn-hongkong.aliyuncs.com
    repo: registry.cn-hongkong.aliyuncs.com/laiwanio/laiwan_io_web_staging
    username:
      from_secret: aliyun_docker_username
    password:
      from_secret: aliyun_docker_password
    tags:
    - ${DRONE_COMMIT_SHA}
    build_args:
    - "--no-cache"
  when:
    event: push
    branch: master

- name: Build staging docker image by tag
  image: plugins/docker
  pull: if-not-exists
  settings:
    registry: registry.cn-hongkong.aliyuncs.com
    repo: registry.cn-hongkong.aliyuncs.com/laiwanio/laiwan_io_web_staging
    username:
      from_secret: aliyun_docker_username
    password:
      from_secret: aliyun_docker_password
    tags:
      - ${DRONE_TAG##v}
    build_args:
    - "--no-cache"
  when:
    event: tag
    branch:
      exclude:
        - master

- name: Set production config
  image: python
  pull: if-not-exists
  commands:
    - cd laiwan-io-web
    - cp src/config_production.json src/config.json
  when:
    event: tag
    branch: master

- name: Build production docker image by tag
  image: plugins/docker
  pull: if-not-exists
  settings:
    registry: registry.cn-hongkong.aliyuncs.com
    repo: registry.cn-hongkong.aliyuncs.com/laiwanio/laiwan_io_web_production
    username:
      from_secret: aliyun_docker_username
    password:
      from_secret: aliyun_docker_password
    tags:
      - ${DRONE_TAG##v}
    build_args:
    - "--no-cache"
  when:
    event: tag
    branch: master

- name: Deploy staging by push master
  image: plugins/ansible
  pull: if-not-exists
  settings:
    playbook: deploy/staging.yml
    inventory: deploy/staging.hosts
    flush_cache: true
    private_key:
      from_secret: aliyun_k8s_ssh_key
    extra_vars: docker_tag=${DRONE_COMMIT_SHA}
  when:
    event: push
    branch: master

- name: Telegram staging change log
  image: appleboy/drone-telegram
  pull: if-not-exists
  settings:
    token: 483423532:AAFwMDyTAJF1Mbzmm7PA-2LSK4w-9bwFh3I
    to: -1001149803042
    message: >
      {{#success build.status}}
        Staging部署 {{repo.name}}: {{commit.message}} by {{ commit.author }}
      {{/success}}
  when:
    event: push
    branch: master

- name: Deploy staging by tag
  image: plugins/ansible
  pull: if-not-exists
  settings:
    playbook: deploy/staging.yml
    inventory: deploy/staging.hosts
    flush_cache: true
    private_key:
      from_secret: aliyun_k8s_ssh_key
    extra_vars: docker_tag=${DRONE_TAG##v}
  when:
    event: tag
    branch:
      exclude:
        - master

- name: Telegram staging change log by tag
  image: appleboy/drone-telegram
  pull: if-not-exists
  settings:
    token: 483423532:AAFwMDyTAJF1Mbzmm7PA-2LSK4w-9bwFh3I
    to: -1001149803042
    message: >
      {{#success build.status}}
        Staging部署 {{repo.name}} [{{ build.tag }}]: {{commit.message}} by {{ commit.author }}
      {{/success}}
  when:
    event: tag

- name: Deploy production by tag
  image: plugins/ansible
  pull: if-not-exists
  settings:
    playbook: deploy/production.yml
    inventory: deploy/production.hosts
    flush_cache: true
    private_key:
      from_secret: aliyun_k8s_ssh_key
    extra_vars: docker_tag=${DRONE_TAG##v}
  when:
    event: tag
    branch: master

- name: Telegram production change log
  image: appleboy/drone-telegram
  pull: if-not-exists
  settings:
    token: 483423532:AAFwMDyTAJF1Mbzmm7PA-2LSK4w-9bwFh3I
    to: -1001451355077
    message: >
      {{#success build.status}}
        Production部署 {{repo.name}} [{{ build.tag }}]: {{commit.message}} by {{ commit.author }}
      {{/success}}
  when:
    event: tag
    branch: master

- name: Telegram when failure
  image: appleboy/drone-telegram
  pull: if-not-exists
  settings:
    token: 483423532:AAFwMDyTAJF1Mbzmm7PA-2LSK4w-9bwFh3I
    to: -1001188725759
  when:
    status: [ failure ]
