#!/bin/bash
echo "这个脚本将帮助你添加一个新的tag，并部署到staging服务器上"

echo "正在获取Remote git上最近的5个Tag ..."
git ls-remote --tags| awk '{print $2}' | sort --version-sort | tail -n 5

read -p "添加一个最新的tag: v" git_tag

git tag v$git_tag || exit
git push origin v$git_tag

echo "Tag v$git_tag 已经同步到Remote"

echo "部署到Staging"
cd k8s-ansible && ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i staging.hosts staging.yml \
    --extra-vars "docker_tag=$git_tag"
