---
- name: Make k8s dir
  remote_user: root
  become: yes
  file: path=k8s mode=0755 state=directory

- name: copy k8s deploy files to server
  synchronize:
    src: k8s/
    dest: k8s/{{ project }}
    rsync_opts: --exclude=.DS_Store
    delete: yes

- name: upload deployment.yaml
  template:
    src: deployment.yaml.tpl
    dest: k8s/{{ project }}/deployment.yaml

- name: Run install-{{ k8s_namespace }}.sh
  shell: ./install-{{ k8s_namespace }}.sh
  args:
    chdir: k8s/{{ project }}
  register: install
- debug: var=install.stdout_lines
