---
- name: Make k8s dir
  remote_user: root
  become: yes
  file: path=k8s_{{ stage }}/{{ project }} mode=0755 state=directory

- name: upload ingress-{{ k8s_namespace }}.yaml
  copy:
    src: k8s/ingress-{{ k8s_namespace }}.yaml
    dest: k8s_{{ stage }}/{{ project }}/ingress-{{ k8s_namespace }}.yaml

- name: upload install-{{ k8s_namespace }}.sh
  copy:
    src: k8s/install-{{ k8s_namespace }}.sh
    dest: k8s_{{ stage }}/{{ project }}/install-{{ k8s_namespace }}.sh
    mode: 0755

- name: upload deployment.yaml
  template:
    src: deployment.yaml.tpl
    dest: k8s_{{ stage }}/{{ project }}/deployment.yaml

- name: Run install-{{ k8s_namespace }}.sh
  shell: ./install-{{ k8s_namespace }}.sh
  args:
    chdir: k8s_{{ stage }}/{{ project }}
  register: install
- debug: var=install.stdout_lines
